In [1]:
import pandas as pd

In [4]:
data = pd.read_excel(
    "Customer Demographic Data Analysis Data.xlsx"
)

In [3]:
data.head()

,Customer_ID,Registration_Date,Gender,Age,City,Occupation,Monthly_Income
0,CUS00005,2025-01-20 00:00:00,Male,49.0,Mogadishu,Healthcare,1024.44
1,CUS00034,NaN,Male,39.0,Baidoa,Teacher,827.25
2,CUS00176,2026-05-31 00:00:00,Male,NaN,Hargeisa,Teacher,661.3
3,CUS00026,2025-10-24 00:00:00,Female,20.0,Mogadishu,Student,295.45
4,CUS00195,2025-12-15 00:00:00,Male,31.0,Bosaso,Self-Employed,481.99

In [5]:
data['Gender']

0        Male
1        Male
2        Male
3      Female
4        Male
        ...
295    Female
296    Female
297    Female
298    Female
299      Male
Name: Gender, Length: 300, dtype: object

In [6]:
data.dtypes

Customer_ID           object
Registration_Date     object
Gender                object
Age                  float64
City                  object
Occupation            object
Monthly_Income        object
dtype: object

In [7]:
data['Occupation'].value_counts()

Occupation
Business Owner    50
Engineer          43
Teacher           42
Self-Employed     40
Student           36
Civil Servant     36
Healthcare        32
CS                 2
CIVIL SERVANT      1
TEACHER            1
student            1
self-employed      1
Name: count, dtype: int64

In [8]:
data.rename(columns={"Customer_ID":"CUD"})

,CUD,Registration_Date,Gender,Age,City,Occupation,Monthly_Income
0,CUS00005,2025-01-20 00:00:00,Male,49.0,Mogadishu,Healthcare,1024.44
1,CUS00034,NaN,Male,39.0,Baidoa,Teacher,827.25
2,CUS00176,2026-05-31 00:00:00,Male,NaN,Hargeisa,Teacher,661.3
3,CUS00026,2025-10-24 00:00:00,Female,20.0,Mogadishu,Student,295.45
4,CUS00195,2025-12-15 00:00:00,Male,31.0,Bosaso,Self-Employed,481.99
...,...,...,...,...,...,...,...
295,CUS00080,2025-03-29 00:00:00,Female,32.0,Mogadishu,self-employed,1235.89
296,CUS00145,2026-04-24 00:00:00,Female,57.0,Kismayo,Business Owner,749.33
297,CUS00049,2025-04-10 00:00:00,Female,33.0,Garowe,Civil Servant,661.71
298,CUS00035,2025-12-31 00:00:00,Female,41.0,Baidoa,Self-Employed,455.83
299,CUS00097,2025-04-03 00:00:00,Male,49.0,Bosaso,Student,NaN

In [9]:
data['Occupation'] = data['Occupation'].replace("CS", "CIVIL SERVANT")

In [10]:
data['Occupation'].value_counts()

Occupation
Business Owner    50
Engineer          43
Teacher           42
Self-Employed     40
Student           36
Civil Servant     36
Healthcare        32
CIVIL SERVANT      3
TEACHER            1
student            1
self-employed      1
Name: count, dtype: int64

In [12]:
data['Gender'].value_counts()

Gender
Female    147
Male      134
male        1
female      1
Name: count, dtype: int64

In [14]:
data['Gender'] = data['Gender'].replace("MALE", "Male")

In [19]:
data['Gender'].value_counts()

Gender
Female    148
Male      135
male        1
-           1
Name: count, dtype: int64

In [17]:
data['Gender'] = data['Gender'].replace("male", "Male")
data['Gender'] = data['Gender'].replace("female", "Female")

In [18]:
data['Gender'].value_counts()

Gender
Female    148
Male      135
Name: count, dtype: int64

In [19]:
data['City'].value_counts()

City
Mogadishu    112
Hargeisa      47
Kismayo       38
Bosaso        37
Baidoa        26
Garowe        22
-              1
mogadishu      1
Name: count, dtype: int64

In [20]:
data['City'] = data['City'].replace("Mogadishu", "Mog")

In [21]:
data['City'].value_counts()

City
Mog          112
Hargeisa      47
Kismayo       38
Bosaso        37
Baidoa        26
Garowe        22
-              1
mogadishu      1
Name: count, dtype: int64

In [22]:
data['Occupation'].value_counts()

Occupation
Business Owner    50
Engineer          43
Teacher           42
Self-Employed     40
Student           36
Civil Servant     36
Healthcare        32
CIVIL SERVANT      3
TEACHER            1
student            1
self-employed      1
Name: count, dtype: int64

In [23]:
data.dtypes

Customer_ID           object
Registration_Date     object
Gender                object
Age                  float64
City                  object
Occupation            object
Monthly_Income        object
dtype: object

In [25]:
data['Age'] = data['Age'].astype(float)

In [27]:
data['Monthly_Income'] = pd.to_numeric(
    data['Monthly_Income'],
    errors="coerce"
)

print(data['Monthly_Income'])

0      1024.44
1       827.25
2       661.30
3       295.45
4       481.99
        ...
295    1235.89
296     749.33
297     661.71
298     455.83
299        NaN
Name: Monthly_Income, Length: 300, dtype: float64