# sorting and Filtering

In [1]:
# import library pandas
# syntax for imprt (import Library_name as pd)
import pandas as pd

In [2]:
# read Data 
data2 = pd.read_excel("Customer Demographic Data Analysis Data.xlsx")
data2.head()

,Customer_ID,Registration_Date,Gender,Age,City,Occupation,Monthly_Income
0,CUS00005,2025-01-20 00:00:00,Male,49.0,Mogadishu,Healthcare,1024.44
1,CUS00034,NaN,Male,39.0,Baidoa,Teacher,827.25
2,CUS00176,2026-05-31 00:00:00,Male,NaN,Hargeisa,Teacher,661.3
3,CUS00026,2025-10-24 00:00:00,Female,20.0,Mogadishu,Student,295.45
4,CUS00195,2025-12-15 00:00:00,Male,31.0,Bosaso,Self-Employed,481.99

#data cleaning

select one column

In [3]:
data2['Gender']

0        Male
1        Male
2        Male
3      Female
4        Male
        ...
295    Female
296    Female
297    Female
298    Female
299      Male
Name: Gender, Length: 300, dtype: object

selecting multi column

In [4]:
data2[['Occupation','City','Monthly_Income']]

         Occupation       City Monthly_Income
0        Healthcare  Mogadishu        1024.44
1           Teacher     Baidoa         827.25
2           Teacher   Hargeisa          661.3
3           Student  Mogadishu         295.45
4     Self-Employed     Bosaso         481.99
..              ...        ...            ...
295   self-employed  Mogadishu        1235.89
296  Business Owner    Kismayo         749.33
297   Civil Servant     Garowe         661.71
298   Self-Employed     Baidoa         455.83
299         Student     Bosaso            NaN

[300 rows x 3 columns]

#select row using tool (data iloc)*italicised text*

select one row

In [5]:
data2.iloc[299]

Customer_ID                     CUS00097
Registration_Date    2025-04-03 00:00:00
Gender                              Male
Age                                 49.0
City                              Bosaso
Occupation                       Student
Monthly_Income                       NaN
Name: 299, dtype: object

select using Multiple row using iloc

In [6]:
# select Multiple rows
data2.iloc[1:10]

,Customer_ID,Registration_Date,Gender,Age,City,Occupation,Monthly_Income
1,CUS00034,NaN,Male,39.0,Baidoa,Teacher,827.25
2,CUS00176,2026-05-31 00:00:00,Male,NaN,Hargeisa,Teacher,661.3
3,CUS00026,2025-10-24 00:00:00,Female,20.0,Mogadishu,Student,295.45
4,CUS00195,2025-12-15 00:00:00,Male,31.0,Bosaso,Self-Employed,481.99
5,CUS00191,2026-02-06 00:00:00,Female,65.0,Hargeisa,Civil Servant,1067.9
6,CUS00060,2025-07-23 00:00:00,Female,47.0,Mogadishu,Self-Employed,444.76
7,CUS00229,2025-09-02 00:00:00,Female,46.0,Mogadishu,NaN,911.36
8,CUS00172,2025-11-09 00:00:00,Female,70.0,Bosaso,Teacher,415.78
9,CUS00233,2026-05-17 00:00:00,Female,39.0,Bosaso,Healthcare,1315.07

#select multiple using loc

In [7]:
data2.loc[1:10]

,Customer_ID,Registration_Date,Gender,Age,City,Occupation,Monthly_Income
1,CUS00034,NaN,Male,39.0,Baidoa,Teacher,827.25
2,CUS00176,2026-05-31 00:00:00,Male,NaN,Hargeisa,Teacher,661.3
3,CUS00026,2025-10-24 00:00:00,Female,20.0,Mogadishu,Student,295.45
4,CUS00195,2025-12-15 00:00:00,Male,31.0,Bosaso,Self-Employed,481.99
5,CUS00191,2026-02-06 00:00:00,Female,65.0,Hargeisa,Civil Servant,1067.9
6,CUS00060,2025-07-23 00:00:00,Female,47.0,Mogadishu,Self-Employed,444.76
7,CUS00229,2025-09-02 00:00:00,Female,46.0,Mogadishu,NaN,911.36
8,CUS00172,2025-11-09 00:00:00,Female,70.0,Bosaso,Teacher,415.78
9,CUS00233,2026-05-17 00:00:00,Female,39.0,Bosaso,Healthcare,1315.07
10,CUS00245,2025-05-04 00:00:00,Male,32.0,Mogadishu,NaN,176.95

selecting row and culomn with loc

In [9]:
## select rows and culomn with loc
data2.loc[10:100,['Gender','Occupation']]

     Gender      Occupation
10     Male             NaN
11   Female  Business Owner
12   Female             NaN
13   Female  Business Owner
14   Female             NaN
..      ...             ...
96   Female   Civil Servant
97   Female         Student
98     Male   Civil Servant
99     Male        Engineer
100     NaN   Self-Employed

[91 rows x 2 columns]

## select rows and culomns using data iloc

Return Integer position

In [10]:
data2.iloc[0]

Customer_ID                     CUS00005
Registration_Date    2025-01-20 00:00:00
Gender                              Male
Age                                 49.0
City                           Mogadishu
Occupation                    Healthcare
Monthly_Income                   1024.44
Name: 0, dtype: object

#selection Multiple row using iloc

In [11]:
data2.iloc[5:10]

,Customer_ID,Registration_Date,Gender,Age,City,Occupation,Monthly_Income
5,CUS00191,2026-02-06 00:00:00,Female,65.0,Hargeisa,Civil Servant,1067.9
6,CUS00060,2025-07-23 00:00:00,Female,47.0,Mogadishu,Self-Employed,444.76
7,CUS00229,2025-09-02 00:00:00,Female,46.0,Mogadishu,NaN,911.36
8,CUS00172,2025-11-09 00:00:00,Female,70.0,Bosaso,Teacher,415.78
9,CUS00233,2026-05-17 00:00:00,Female,39.0,Bosaso,Healthcare,1315.07

#select Row and Column using iloc

In [12]:
data2.iloc[5:10,3:7]

    Age       City     Occupation Monthly_Income
5  65.0   Hargeisa  Civil Servant         1067.9
6  47.0  Mogadishu  Self-Employed         444.76
7  46.0  Mogadishu            NaN         911.36
8  70.0     Bosaso        Teacher         415.78
9  39.0     Bosaso     Healthcare        1315.07

# Filtering Data

Numerial Filter

In [14]:
data2[data2['Occupation'] == 'Civil Servant']

,Customer_ID,Registration_Date,Gender,Age,City,Occupation,Monthly_Income
5,CUS00191,2026-02-06 00:00:00,Female,65.0,Hargeisa,Civil Servant,1067.9
16,CUS00227,2025-05-03 00:00:00,Female,37.0,Mogadishu,Civil Servant,1041.84
26,CUS00023,2026-03-01 00:00:00,Female,32.0,Kismayo,Civil Servant,558.07
27,CUS00040,2025-09-25 00:00:00,Female,66.0,Mogadishu,Civil Servant,656.1
44,CUS00236,2026-02-14 00:00:00,Female,22.0,Hargeisa,Civil Servant,1164.05
46,CUS00225,2025-11-14 00:00:00,NaN,70.0,Mogadishu,Civil Servant,395.84
69,NaN,2026-02-07 00:00:00,Male,23.0,Kismayo,Civil Servant,528.86
79,CUS00238,2026-06-11 00:00:00,Male,62.0,Garowe,Civil Servant,595.7
90,CUS00022,NaN,Female,55.0,Mogadishu,Civil Servant,618.43
91,CUS00071,NaN,Female,48.0,Garowe,Civil Servant,759.9
96,CUS00049,NaN,Female,NaN,Garowe,Civil Servant,661.71
98,CUS00007,2025-08-05 00:00:00,Male,45.0,Mogadishu,Civil Servant,839.71
107,CUS00201,2026-02-17 00:00:00,Female,55.0,Hargeisa,Civil Servant,1021.22
137,CUS00021,2025-06-04 00:00:00,Female,19.0,Mogadishu,Civil Servant,NaN
170,CUS00271,2025-04-06 00:00:00,Female,48.0,Garowe,Civil Servant,746.26
186,CUS00262,2025-05-03 00:00:00,Male,67.0,Mogadishu,Civil Servant,NaN
191,CUS00006,2025-01-08 00:00:00,Female,40.0,Bosaso,Civil Servant,789.1
196,CUS00136,2025-03-18 00:00:00,Male,32.0,Baidoa,Civil Servant,707.01
201,CUS00206,2025-02-06 00:00:00,Female,20.0,Mogadishu,Civil Servant,NaN
205,CUS00033,2025-10-02 00:00:00,Male,54.0,Kismayo,Civil Servant,1108.62
206,CUS00096,2026-02-07 00:00:00,NaN,33.0,Mogadishu,Civil Servant,930.02
216,CUS00216,2025-09-19 00:00:00,Female,19.0,Hargeisa,Civil Servant,916.62
239,CUS00234,2025-04-11 00:00:00,NaN,40.0,Kismayo,Civil Servant,641.59
241,CUS00276,2025-03-28 00:00:00,Male,20.0,Hargeisa,Civil Servant,389.22
248,CUS00043,2025-06-25 00:00:00,NaN,43.0,Mogadishu,Civil Servant,885.26
254,CUS00193,2026-07-07 00:00:00,Male,61.0,Mogadishu,Civil Servant,1071.86
258,CUS00247,2025-04-05 00:00:00,Female,39.0,Garowe,Civil Servant,396.11
261,CUS00031,NaN,Female,28.0,Baidoa,Civil Servant,647.6
262,CUS00040,2025-09-25 00:00:00,Female,66.0,Mogadishu,Civil Servant,656.1
285,CUS00161,2025-11-12 00:00:00,Male,20.0,Kismayo,Civil Servant,872.34
286,CUS00139,2025-10-04 00:00:00,Male,27.0,Bosaso,Civil Servant,897.29
287,CUS00111,2025-03-25 00:00:00,Female,48.0,Baidoa,Civil Servant,523.37
291,CUS00024,2026-04-17 00:00:00,Female,18.0,Mogadishu,Civil Servant,1155.56
292,CUS00282,2025-10-26 00:00:00,Male,34.0,Bosaso,Civil Servant,862.99
293,CUS00253,2026-05-08 00:00:00,Male,67.0,Mogadishu,Civil Servant,857.27
297,CUS00049,2025-04-10 00:00:00,Female,33.0,Garowe,Civil Servant,661.71

Filtering multi Categories

In [15]:
data2[data2['Gender'].isin(['Female','NaN'])]

,Customer_ID,Registration_Date,Gender,Age,City,Occupation,Monthly_Income
3,CUS00026,2025-10-24 00:00:00,Female,20.0,Mogadishu,Student,295.45
5,CUS00191,2026-02-06 00:00:00,Female,65.0,Hargeisa,Civil Servant,1067.9
6,CUS00060,2025-07-23 00:00:00,Female,47.0,Mogadishu,Self-Employed,444.76
7,CUS00229,2025-09-02 00:00:00,Female,46.0,Mogadishu,NaN,911.36
8,CUS00172,2025-11-09 00:00:00,Female,70.0,Bosaso,Teacher,415.78
...,...,...,...,...,...,...,...
291,CUS00024,2026-04-17 00:00:00,Female,18.0,Mogadishu,Civil Servant,1155.56
295,CUS00080,2025-03-29 00:00:00,Female,32.0,Mogadishu,self-employed,1235.89
296,CUS00145,2026-04-24 00:00:00,Female,57.0,Kismayo,Business Owner,749.33
297,CUS00049,2025-04-10 00:00:00,Female,33.0,Garowe,Civil Servant,661.71
298,CUS00035,2025-12-31 00:00:00,Female,41.0,Baidoa,Self-Employed,455.83

# Multi Condition

In [16]:
data2[
    (data2['Gender'] == 'Female') &
    (data2['Occupation'] == 'Civil Servant') &
    (data2['City'] =='Mogadishu')
]

,Customer_ID,Registration_Date,Gender,Age,City,Occupation,Monthly_Income
16,CUS00227,2025-05-03 00:00:00,Female,37.0,Mogadishu,Civil Servant,1041.84
27,CUS00040,2025-09-25 00:00:00,Female,66.0,Mogadishu,Civil Servant,656.1
90,CUS00022,NaN,Female,55.0,Mogadishu,Civil Servant,618.43
137,CUS00021,2025-06-04 00:00:00,Female,19.0,Mogadishu,Civil Servant,NaN
201,CUS00206,2025-02-06 00:00:00,Female,20.0,Mogadishu,Civil Servant,NaN
262,CUS00040,2025-09-25 00:00:00,Female,66.0,Mogadishu,Civil Servant,656.1
291,CUS00024,2026-04-17 00:00:00,Female,18.0,Mogadishu,Civil Servant,1155.56

# Sorting Data Sorting Values funcation

In [17]:
data2.sort_values('Gender', ascending=True)

,Customer_ID,Registration_Date,Gender,Age,City,Occupation,Monthly_Income
147,CUS00154,2025-07-26 00:00:00,Female,60.0,Hargeisa,Business Owner,785.37
117,CUS00235,2025-01-24 00:00:00,Female,19.0,Garowe,Teacher,579.55
118,CUS00122,2025-08-17 00:00:00,Female,60.0,Hargeisa,Self-Employed,712.55
119,NaN,2026-05-09 00:00:00,Female,50.0,Mogadishu,Self-Employed,917.25
121,CUS00037,2026-05-15 00:00:00,Female,61.0,Hargeisa,Student,294.94
...,...,...,...,...,...,...,...
259,CUS00184,2025-12-17 00:00:00,NaN,64.0,Bosaso,Self-Employed,638.53
260,CUS00072,2025-03-05 00:00:00,NaN,29.0,Mogadishu,Engineer,1516.2
264,CUS00279,2025-01-17 00:00:00,NaN,18.0,Garowe,Student,312.77
269,CUS00129,2026-05-31 00:00:00,NaN,49.0,Kismayo,Self-Employed,1046.17
278,CUS00016,2025-12-31 00:00:00,NaN,33.0,Mogadishu,Teacher,790.38

In [18]:
data2.sort_values('Gender', ascending=False)

,Customer_ID,Registration_Date,Gender,Age,City,Occupation,Monthly_Income
175,CUS00254,2025-07-19 00:00:00,male,28.0,Baidoa,Student,152.92
209,CUS00197,2025-06-13 00:00:00,female,48.0,Mogadishu,Teacher,921.62
186,CUS00262,2025-05-03 00:00:00,Male,67.0,Mogadishu,Civil Servant,NaN
164,CUS00187,2025-05-18 00:00:00,Male,26.0,Kismayo,Student,267.12
165,CUS00160,2025-08-10 00:00:00,Male,42.0,Hargeisa,Business Owner,1672.71
...,...,...,...,...,...,...,...
259,CUS00184,2025-12-17 00:00:00,NaN,64.0,Bosaso,Self-Employed,638.53
260,CUS00072,2025-03-05 00:00:00,NaN,29.0,Mogadishu,Engineer,1516.2
264,CUS00279,2025-01-17 00:00:00,NaN,18.0,Garowe,Student,312.77
269,CUS00129,2026-05-31 00:00:00,NaN,49.0,Kismayo,Self-Employed,1046.17
278,CUS00016,2025-12-31 00:00:00,NaN,33.0,Mogadishu,Teacher,790.38